#!/usr/bin/env python3
"""Write LaTeX for the two-column (Latin | English) print book from data/corpus.json.

Usage:
  python3 matins/tools/build_latex.py [GROUP ...] [-o NAME]

GROUP is a season id as used in build_epub.py (adv, nat, epi, quadp, quad,
pass, pasc, pent0, pent, m8, m9, m10, m11), "comm" for the Commons, or a
Proper of Saints month (s11a = 29-30 Nov, s12, s1 ... s11b). With no GROUP,
everything. Writes matins/book/NAME.tex; compile with
  latexmk -lualatex -cd matins/book/NAME.tex
The page design is in matins/book/matins.sty.
"""

import argparse
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import build_corpus as B  # noqa: E402
import build_epub as E  # noqa: E402
import layout  # noqa: E402
import credits  # noqa: E402

_TEX = {"\\": r"\textbackslash{}", "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#", "_": r"\_",
        "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}", "^": r"\textasciicircum{}"}


def tex(s):
    return "".join(_TEX.get(c, c) for c in (s or ""))


def stars(s):
    return tex(s).replace(" * ", r" \Star{} ")


def resp_item(item):
    if item[0] == "R":
        t = tex(item[1]) + (r" \Star{} " + tex(item[2]) if item[2] else "")
        return r"\begin{Resp}\Rsign " + t + r"\end{Resp}"
    return r"\begin{Resp}\Vsign " + stars(item[1]) + r"\end{Resp}"


def cell(kind, items, first_text):
    if kind == "resp":
        return "\n".join(resp_item(i) for i in items)
    if kind == "text":
        out = []
        for i, p in enumerate(items):
            out.append((r"\noindent " if first_text and i == 0 else "") + tex(p) + r"\par")
        return "\n".join(out)
    cmd = {"head": "LessonHead", "title": "LessonTitle", "cite": "Cite", "source": "Source",
           "rubric": "Rubric", "note": "Note", "tedeum": "TeDeum"}[kind]
    return "\n".join(f"\\{cmd}{{{tex(i)}}}" for i in items)


def row(la, en):
    return f"\\LA\n{la}\n\\switchcolumn\n\\EN\n{en}\n\\switchcolumn*\n"


def office(e, codes):
    out = []
    date = ""
    if e["kind"] == "Sancti":
        date = E.sancti_date(e["file"], "latin")
    title_la = tex(e["title_latin"])
    title_en = tex(e["title_english"])
    rank = tex(e.get("rank") or "")
    if date:
        out.append(f"\\par\\needspace{{10\\baselineskip}}\\addvspace{{1.2em}}"
                   f"{{\\centering\\small\\textsc{{{tex(date)}}} · \\textsc{{{tex(E.sancti_date(e['file'], 'english'))}}}\\par}}")
    out.append(f"\\Office{{{title_la}}}{{{title_en}}}{{{rank}}}")
    out.append(r"\begin{paracol}{2}")
    if e.get("see"):
        code = tex(E.stem(e["see"]))
        out.append(row(f"\\RefLine{{Cetera ut in {code}.}}", f"\\RefLine{{Otherwise as in {code}.}}"))
    for la, en in E.ref_lines(e, {}):
        strip = lambda h: re.sub(r"<[^>]+>", "", h)
        import html as _h
        out.append(row(f"\\RefLine{{{tex(_h.unescape(strip(la)))}}}", f"\\RefLine{{{tex(_h.unescape(strip(en)))}}}"))
    for les in e["lessons"]:
        note = les.get("note", "")
        rows = layout.lesson_rows(les["n"], les["latin"], les["english"],
                                  B.NOTE["latin"].get(note, note), B.NOTE["english"].get(note, note),
                                  untranslated=B.untranslated(les))
        # In print each language's responsory flows as one block; pairing its
        # lines would leave gaps wherever the English runs longer.
        merged = []
        for kind, la, en in rows:
            if kind == "resp" and merged and merged[-1][0] == "resp":
                merged[-1] = ("resp", merged[-1][1] + la, merged[-1][2] + en)
            else:
                merged.append((kind, list(la), list(en)))
        first = True
        for kind, la, en in merged:
            out.append(row(cell(kind, la, first), cell(kind, en, first)))
            first = kind != "text"
    out.append(r"\end{paracol}")
    return "\n".join(out)


def credits_tex():
    out = [r"{\footnotesize\setlength{\parindent}{0pt}\setlength{\parskip}{0.35em}\raggedright"]
    for h, ps in credits.sections(print_book=True):
        out.append(f"\\par\\addvspace{{0.6em}}\\textsc{{{tex(h)}}}\\par")
        out.extend(tex(p) + r"\par" for p in ps)
    out.append("}")
    return "\n".join(out)


def document(selected, title_note):
    parts_out = []
    for pid, pla, pen, groups in selected:
        parts_out.append(f"\\PartTitle{{{tex(pla)}}}{{{tex(pen)}}}")
        for gid, gla, gen, es in groups:
            if len(groups) > 1 or pid != "commune":
                parts_out.append(f"\\SeasonTitle{{{tex(gla)}}}{{{tex(gen)}}}")
            for e in es:
                parts_out.append(office(e, {}))
    body = "\n\n".join(parts_out)
    return rf"""% Generated by matins/tools/build_latex.py from data/corpus.json — do not edit.
\documentclass[10pt,twoside,openright]{{book}}
\usepackage{{matins}}
\begin{{document}}
\BodySize
\frontmatter
\thispagestyle{{empty}}
\vspace*{{0.25\textheight}}
{{\centering
{{\Huge\rubr{{{tex(E.TITLE_LA)}}}}}\par\vspace{{0.4em}}
{{\large\itshape {tex(E.SUBTITLE_LA)}}}\par\vspace{{2em}}
{{\LARGE {tex(E.TITLE_EN)}}}\par\vspace{{0.4em}}
{{\large\itshape {tex(E.SUBTITLE_EN)}}}\par\vspace{{3em}}
{{\small {tex(title_note)}}}\par}}
\clearpage
\thispagestyle{{empty}}
{credits_tex()}
\mainmatter
{body}
\end{{document}}
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("groups", nargs="*")
    ap.add_argument("-o", "--output", default=None)
    args = ap.parse_args()

    corpus = json.load(open(os.path.join(ROOT, "data", "corpus.json"), encoding="utf-8"))
    parts = E.build_structure(corpus)
    want = set(args.groups)
    selected = []
    for pid, pla, pen, groups in parts:
        gs = [g for g in groups if not want or g[0] in want or pid in want]
        if gs:
            selected.append((pid, pla, pen, gs))
    if not selected:
        sys.exit(f"no such group: {', '.join(args.groups)}")
    name = args.output or ("matins" if not want else "-".join(args.groups))
    note = "Sample: " + ", ".join(g[2] for _, _, _, gs in selected for g in gs) if want else ""
    path = os.path.join(ROOT, "book", name + ".tex")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(document(selected, note))
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
